Document: sam-forwarder
Title: Debian sam-forwarder Manual
Author: <insert document author here>
Abstract: This manual describes what sam-forwarder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sam-forwarder/sam-forwarder.sgml.gz

Format: postscript
Files: /usr/share/doc/sam-forwarder/sam-forwarder.ps.gz

Format: text
Files: /usr/share/doc/sam-forwarder/sam-forwarder.text.gz

Format: HTML
Index: /usr/share/doc/sam-forwarder/html/index.html
Files: /usr/share/doc/sam-forwarder/html/*.html
